language: objective-c

env:
 global:
  - EnableNuGetPackageRestore=true 
 matrix:
  - MONO_VERSION="3.4.0"

before_install:
 - wget "http://download.mono-project.com/archive/3.4.0/macos-10-x86/MonoFramework-MDK-3.4.0.macos10.xamarin.x86.pkg"
 - sudo installer -pkg "MonoFramework-MDK-3.4.0.macos10.xamarin.x86.pkg" -target /
 - chmod +x ./xunit.sh 

script:
  - xbuild FeatureFlipper.sln
  - ./xunit.sh test/FeatureFlipper.Tests/bin/Debug/FeatureFlipper.Tests.dll 
# test/FeatureFlipper.Unity.Tests/bin/Debug/FeatureFlipper.Unity.Tests.dll test/FeatureFlipper.WebApi.Tests/bin/Debug/FeatureFlipper/WebApi.Tests.dll
