//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureFlipper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FeatureFlipper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature &apos;{0}&apos; is already registered..
        /// </summary>
        internal static string Feature_AlreadyRegistered {
            get {
                return ResourceManager.GetString("Feature_AlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following features have cyclic dependencies :.
        /// </summary>
        internal static string Feature_CyclicDependencies {
            get {
                return ResourceManager.GetString("Feature_CyclicDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one feature have the same feature name :.
        /// </summary>
        internal static string Feature_Duplicate {
            get {
                return ResourceManager.GetString("Feature_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No provider of type {0} were found in the Providers property..
        /// </summary>
        internal static string Feature_NoProvider {
            get {
                return ResourceManager.GetString("Feature_NoProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feature &apos;{0}&apos; or one of its dependency is unknown..
        /// </summary>
        internal static string Feature_Unknown {
            get {
                return ResourceManager.GetString("Feature_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The type {0} is not a valid service type..
        /// </summary>
        internal static string Service_Invalid {
            get {
                return ResourceManager.GetString("Service_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service type {0} is not supported..
        /// </summary>
        internal static string Service_Unsupported {
            get {
                return ResourceManager.GetString("Service_Unsupported", resourceCulture);
            }
        }
    }
}
